<Project>
	<PropertyGroup>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<PropertyGroup>
		<!--<ArtifactsPath>$(MSBuildThisFileDirectory)..\..\artifacts</ArtifactsPath>-->
		<PackageOutputPath>$(MSBuildThisFileDirectory)..\..\artifacts\packages</PackageOutputPath>
		<PublishDir>$(MSBuildThisFileDirectory)..\..\artifacts\publish\$(MSBuildProjectName)\$(TargetFramework)\$(RuntimeIdentifier)</PublishDir>
	</PropertyGroup>

	<PropertyGroup>
		<TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageIcon>RestlingIcon.png</PackageIcon>
		<PackageProjectUrl>https://github.com/AMDevIT/Restling</PackageProjectUrl>
		<RepositoryUrl>https://github.com/AMDevIT/Restling.git</RepositoryUrl>
		<PackageTags>rest;http;httpclient;api;apiclient;client;restclient;dotnet;csharp;networking;web;request;response;json;xml;serialization;deserialization;async;await;typed-client;fluent;builder;wrapper</PackageTags>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<Version>$(VersionPrefix)$(VersionSuffix)</Version>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<IsPackable>true</IsPackable>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
		<EnablePackageValidation>true</EnablePackageValidation>
		<Authors>Alessandro Morvillo</Authors>
		<Company>AMDev.IT di Alessandro Morvillo</Company>
		<Copyright>© 2025 Alessandro Morvillo</Copyright>
		<VersionPrefix>1.55.6.0</VersionPrefix>
		<VersionSuffix>alpha3</VersionSuffix>
		<AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
	</PropertyGroup>
</Project>
