<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Restling.Csv</PackageId>
		<Description>Optional CSV content codec for Restling, powered by CsvHelper.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/AMDevIT/Restling.git</RepositoryUrl>
		<Title>Restling CSV Content codec</Title>
		<!--<PackageIcon>RestlingIcon.png</PackageIcon>-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\AMDevIT.Restling.Core\AMDevIT.Restling.Core.csproj" />
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<None Include="..\..\..\Assets\Icons\RestlingIcon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
